version: '3.9'

services:
  postgresql:
    image: postgres:17.5-alpine3.22
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - barn_pgdata:/var/lib/postgresql/data/pgdata
      - ../migrations/postgresql:/docker-entrypoint-initdb.d
    env_file:
      - ../config/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - barn_data_network

networks:
  barn_data_network:

volumes:
  barn_pgdata: